### ISSUE TITLE
getRGBVolume failed when LUT is off and number of channels is larger than 3

### ISSUE THREAD

**Issue by tryphoncosinus** [Ajaxels/MIB2#4]
Hello,

With LUT unchecked and 4 channels, getRGBVolume produces the following error:

Index in position 1 exceeds array bounds. Index must not exceed 3.

Error in mibModel/getRGBvolume (line 87)
        R = R + imgOut*255*selectedColorsLUT(colCh, 1);

Adding this code after line 63 : 

`colorIndices = colorIndices(1:min(3,numel(colorIndices)));`

solved the issue. In that way, to get more than 3 channels successfully rendered, user must check LUT or he gets only 3 channels.

Thanks for useful MIB2 software.

MIB 2.9012

**Comment by Ajaxels** [comment]
Hi @tryphoncosinus ,
thank you, I added that, it will come when I update the source next time.
It is however quite old software rendering engine and it is better to use File->Menu->Render volume->MIB rendering
https://youtu.be/840o6zni3KE?si=PfA2BnJsmySl4CI8

**Comment by tryphoncosinus** [comment]
Hello Ajaxels,

Oh yes, new rendering tools are better and smoother of course and I use them to visualise my FIB-SEM data (R2018-2021). However, for multiphoton microscopy images (4D / 5D), the old rendering way helps a lot to see colocalized signals and time evolution. Maybe it is possible to turn channels into materials and visualise them as in the video you pointed  out but I did not explored that yet.

Thank you for your huge work.

**Comment by Ajaxels** [comment]
I checked, it is possible to visualize grayscale or RGB volumes using the new hardware rendering engine. If you have 2 or 3 color channels, you should be able to visualize them. If you have 4 color channels, the current version will give you an error.
I fixed that already, but the final result that max number of simultaneously shown color channels is 3 and there is no possibility to change their color map to match colors of fluorophores. This will be available in next beta/normal release.
