### ISSUE TITLE
Cannot find dll files in path when compiling

### ISSUE THREAD

**Issue by ghost** [Ajaxels/MIB2#5]
Hi

I see that there are many dll files added in dependencies and I cannot find them in Matlab path. The compilation did not work.
How can I get these DLLs files? I think I installed all required toolboxes.
I'm using Matlab R2024a.

---------
      <file>C:\ProgramData\MATLAB\SupportPackages\R2024a\bin\win64\asmjit.dll</file>
      <file>C:\ProgramData\MATLAB\SupportPackages\R2024a\bin\win64\c10.dll</file>
      <file>C:\ProgramData\MATLAB\SupportPackages\R2024a\bin\win64\fbgemm.dll</file>
      <file>C:\ProgramData\MATLAB\SupportPackages\R2024a\bin\win64\leveldb.dll</file>
      <file>C:\ProgramData\MATLAB\SupportPackages\R2024a\bin\win64\libtorch.rights</file>
      <file>C:\ProgramData\MATLAB\SupportPackages\R2024a\bin\win64\onnxpb.dll</file>
      <file>C:\ProgramData\MATLAB\SupportPackages\R2024a\bin\win64\tfkeraspb.dll</file>
      <file>C:\ProgramData\MATLAB\SupportPackages\R2024a\bin\win64\torch_cpu.dll</file>
-------

Thanks a lot.
Lam

**Comment by Ajaxels** [comment]
Hi,
as the easiest solution, you can click on the Settings button in application compiler and take away Additional parameters passed to mcc.

**Comment by ptlzon** [comment]
Hi,
Now I could compile the app. Thanks a lot.
